# Generated by Django 5.2.15 on 2026-07-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(null=True)),
                ("listings_seen", models.IntegerField(default=0)),
                ("inserted", models.IntegerField(default=0)),
                ("updated", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_site",
                    models.CharField(
                        choices=[
                            ("batdongsan", "batdongsan"),
                            ("maisonoffice", "maisonoffice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(max_length=64)),
                ("url", models.URLField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("category_id_source", models.IntegerField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "apartment"),
                            ("house", "house"),
                            ("land", "land"),
                            ("villa", "villa"),
                            ("office", "office"),
                        ],
                        max_length=20,
                    ),
                ),
                ("project_name", models.CharField(max_length=255, null=True)),
                ("project_id_source", models.CharField(max_length=64, null=True)),
                (
                    "listing_intent",
                    models.CharField(
                        choices=[("sale", "sale"), ("rent", "rent")], max_length=10
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("vip_type", models.CharField(max_length=50, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=0, max_digits=15, null=True),
                ),
                ("price_unit", models.CharField(max_length=50, null=True)),
                (
                    "price_per_sqm",
                    models.DecimalField(decimal_places=0, max_digits=15, null=True),
                ),
                (
                    "area_sqm",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("bedrooms", models.IntegerField(null=True)),
                ("bathrooms", models.IntegerField(null=True)),
                ("address_raw", models.TextField(null=True)),
                ("district_id_source", models.IntegerField(null=True)),
                ("ward_id_source", models.IntegerField(null=True)),
                ("district", models.CharField(max_length=100, null=True)),
                ("ward", models.CharField(max_length=100, null=True)),
                ("specs_raw", models.JSONField(null=True)),
                ("description", models.TextField(null=True)),
                ("images", models.JSONField(null=True)),
                ("video_url", models.URLField(null=True)),
                (
                    "map_lat",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "map_lng",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                ("agent_name", models.CharField(max_length=255, null=True)),
                ("agent_id_source", models.CharField(max_length=64, null=True)),
                ("phone_number", models.CharField(max_length=32, null=True)),
                ("posted_date", models.DateField(null=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("delisted_at", models.DateTimeField(null=True)),
                (
                    "predicted_price",
                    models.DecimalField(decimal_places=0, max_digits=15, null=True),
                ),
                ("predicted_at", models.DateTimeField(null=True)),
                ("is_anomaly", models.BooleanField(default=False)),
                ("anomaly_reason", models.JSONField(null=True)),
            ],
            options={
                "unique_together": {("source_site", "source_id")},
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=0, max_digits=15)),
                (
                    "price_per_sqm",
                    models.DecimalField(decimal_places=0, max_digits=15, null=True),
                ),
                ("observed_at", models.DateTimeField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
            ],
        ),
    ]
