# Generated by Django 5.2.15 on 2026-07-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="agent_id_source",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="agent_name",
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_site",
                    models.CharField(
                        choices=[
                            ("batdongsan", "batdongsan"),
                            ("maisonoffice", "maisonoffice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255, null=True)),
            ],
            options={
                "unique_together": {("source_site", "source_id")},
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="listings.agent",
            ),
        ),
    ]
