# Generated by Django 5.2.15 on 2026-07-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_add_agent_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="url",
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
