# Generated by Django 5.2.15 on 2026-07-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_add_multi_source_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
    ]
