# Generated by Django 5.2.15 on 2026-07-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_pricehistory_price_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperun",
            name="posted_date_nulls",
            field=models.IntegerField(default=0),
        ),
    ]
