# Generated by Django 5.2.15 on 2026-08-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_add_posted_date_null_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="anomaly_scored_at",
            field=models.DateTimeField(null=True),
        ),
    ]
