# Generated by Django 5.2.15 on 2026-08-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_add_anomaly_scored_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(null=True)),
                ("predicted", models.IntegerField(default=0)),
                ("scored", models.IntegerField(default=0)),
                ("flagged", models.IntegerField(default=0)),
                ("n_compared", models.IntegerField(default=0)),
                (
                    "mae_vnd",
                    models.DecimalField(decimal_places=0, max_digits=15, null=True),
                ),
                (
                    "median_ape",
                    models.DecimalField(decimal_places=4, max_digits=6, null=True),
                ),
                ("model_fingerprint", models.CharField(max_length=12, null=True)),
                ("error_count", models.IntegerField(default=0)),
                ("status_counts", models.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="scraperun",
            name="status_counts",
            field=models.JSONField(null=True),
        ),
    ]
