# Generated by Django 5.2.15 on 2026-10-03 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_add_run_status_and_scoring_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(max_length=64, unique=True)),
                ("url", models.URLField(max_length=500, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=100, null=True)),
                ("ward", models.CharField(max_length=100, null=True)),
                ("address_raw", models.TextField(null=True)),
                ("grade", models.CharField(max_length=2, null=True)),
                (
                    "rent_min_usd",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "rent_max_usd",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "service_fee_usd",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "typical_floor_sqm",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("specs_raw", models.JSONField(null=True)),
                ("source_modified_at", models.DateTimeField(null=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("delisted_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OfficeRentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rent_min_usd",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "rent_max_usd",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                ("observed_at", models.DateTimeField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.officebuilding",
                    ),
                ),
            ],
        ),
    ]
